/* spu_images.c -- GENERATED by tools/build_spu_workloads.py.
 * Registers the 10 lifted SPU images of "scottpilgrim" with the workload
 * dispatch registry (by FNV-1a-64 image fingerprint) and populates each image's
 * indirect-branch table under a distinct image id. cellSpurs AddWorkload/
 * CreateTask/RunJobChain call spu_workload_dispatch(), which fingerprints the
 * guest image, finds the lifted entry here, and runs it on a fresh local store.
 * Build note: add <repo>/runtime/spu to this target's include dirs (the lifted
 * sources use bare #include "spu_context.h" etc.). */
#include "spu_workload.h"

extern void spu_begin_image(int image_id);

/* per-image extern decls (prefixed entry fn + recomp_register) */
extern void spu_0000_at_013D5B00_spu_func_00003070(spu_context*);
extern void spu_0000_at_013D5B00_spu_recomp_register(void);
extern void spu_0001_at_013E1F80_spu_func_00003050(spu_context*);
extern void spu_0001_at_013E1F80_spu_recomp_register(void);
extern void spu_0002_at_013F2700_spu_func_00000098(spu_context*);
extern void spu_0002_at_013F2700_spu_recomp_register(void);
extern void spu_0003_at_013F4980_spu_func_00000090(spu_context*);
extern void spu_0003_at_013F4980_spu_recomp_register(void);
extern void spu_0004_at_013F5200_spu_func_00000090(spu_context*);
extern void spu_0004_at_013F5200_spu_recomp_register(void);
extern void spu_0005_at_013F5D00_spu_func_00000548(spu_context*);
extern void spu_0005_at_013F5D00_spu_recomp_register(void);
extern void spu_0006_at_013F7B80_spu_func_00000098(spu_context*);
extern void spu_0006_at_013F7B80_spu_recomp_register(void);
extern void spu_0007_at_01592880_spu_func_000002F0(spu_context*);
extern void spu_0007_at_01592880_spu_recomp_register(void);
extern void spu_0008_at_01594100_spu_func_000008F0(spu_context*);
extern void spu_0008_at_01594100_spu_recomp_register(void);
extern void spu_0009_at_01596700_spu_func_000002F0(spu_context*);
extern void spu_0009_at_01596700_spu_recomp_register(void);

void scottpilgrim_spu_register_all(void)
{
    spu_begin_image(1); spu_0000_at_013D5B00_spu_recomp_register();
    spu_workload_register_img(0x5CFFBA88D1D9616DULL, spu_0000_at_013D5B00_spu_func_00003070, 1, "spu_0000_at_013D5B00");
    spu_begin_image(2); spu_0001_at_013E1F80_spu_recomp_register();
    spu_workload_register_img(0xB8D923CF62CDEAFFULL, spu_0001_at_013E1F80_spu_func_00003050, 2, "spu_0001_at_013E1F80");
    spu_begin_image(3); spu_0002_at_013F2700_spu_recomp_register();
    spu_workload_register_img(0x206C41A83C2CBF0CULL, spu_0002_at_013F2700_spu_func_00000098, 3, "spu_0002_at_013F2700");
    spu_begin_image(4); spu_0003_at_013F4980_spu_recomp_register();
    spu_workload_register_img(0x3A1702380B958DE5ULL, spu_0003_at_013F4980_spu_func_00000090, 4, "spu_0003_at_013F4980");
    spu_begin_image(5); spu_0004_at_013F5200_spu_recomp_register();
    spu_workload_register_img(0xE7BEB4FB9EA75C3DULL, spu_0004_at_013F5200_spu_func_00000090, 5, "spu_0004_at_013F5200");
    spu_begin_image(6); spu_0005_at_013F5D00_spu_recomp_register();
    spu_workload_register_img(0x847F0AEC3B658A50ULL, spu_0005_at_013F5D00_spu_func_00000548, 6, "spu_0005_at_013F5D00");
    spu_begin_image(7); spu_0006_at_013F7B80_spu_recomp_register();
    spu_workload_register_img(0x6BD25DEDAC2C682FULL, spu_0006_at_013F7B80_spu_func_00000098, 7, "spu_0006_at_013F7B80");
    spu_begin_image(8); spu_0007_at_01592880_spu_recomp_register();
    spu_workload_register_img(0x6FE491A1712B898BULL, spu_0007_at_01592880_spu_func_000002F0, 8, "spu_0007_at_01592880");
    spu_begin_image(9); spu_0008_at_01594100_spu_recomp_register();
    spu_workload_register_img(0x4729F9DF85A56059ULL, spu_0008_at_01594100_spu_func_000008F0, 9, "spu_0008_at_01594100");
    spu_begin_image(10); spu_0009_at_01596700_spu_recomp_register();
    spu_workload_register_img(0x5FF188A7846387B9ULL, spu_0009_at_01596700_spu_func_000002F0, 10, "spu_0009_at_01596700");
    spu_begin_image(0);
}

/* Auto-register at startup (before the game adds any SPURS workload/task). */
__attribute__((constructor)) static void scottpilgrim_spu_register_all_ctor(void)
{
    scottpilgrim_spu_register_all();
}
